### ISSUE TITLE
메인 페이지 개발

### ISSUE THREAD

**Issue by grantedfornothing** [Boldwork-AIproject/boldwork_frontend#1]
메인 페이지 개발

**Comment by ganyunhee** [comment]
이슈 : 윈도우 resize할 때 내비세이션 메뉴 안의 링크들이 세로로 나타남 (가로로 고정할 것)

**Comment by ganyunhee** [comment]
## Fixes
---
- 내비게이션 메뉴 wrapping 이슈 해결

## 기타
---
- Components 미리보기 페이지 commented out (10.18)
