### ISSUE TITLE
고객 정보 확인 페이지 개발

### ISSUE THREAD

**Issue by grantedfornothing** [Boldwork-AIproject/boldwork_frontend#11]
고객 정보 확인 페이지 개발

**Comment by ganyunhee** [comment]
레이아웃 완성 (10.13)
코드 병합 (10.15)

<img width="777" alt="image" src="https://github.com/Boldwork-AIproject/boldwork_frontend/assets/81596122/145d62e2-1523-426d-87b3-5778c3af67ed">
