### ISSUE TITLE
고객 상세정보 페이지 개발

### ISSUE THREAD

**Issue by grantedfornothing** [Boldwork-AIproject/boldwork_frontend#12]
고객 상세정보 페이지 개발

**Comment by ganyunhee** [comment]
레이아웃 완성 (10.13)
코드 병합 (10.15)

<img width="782" alt="image" src="https://github.com/Boldwork-AIproject/boldwork_frontend/assets/81596122/ceca97b7-708d-4073-b90e-27f552813702">
