### ISSUE TITLE
로그인 페이지 개발

### ISSUE THREAD

**Issue by grantedfornothing** [Boldwork-AIproject/boldwork_frontend#2]
로그인 페이지 개발

**Comment by ganyunhee** [comment]
레이아웃 완성 (10.14)

<img width="1280" alt="image" src="https://github.com/Boldwork-AIproject/boldwork_frontend/assets/81596122/ec602364-3de1-452a-b8d1-20d79ca1034c">

**Comment by ganyunhee** [comment]
Closed
