### ISSUE TITLE
고객 선택 페이지 개발

### ISSUE THREAD

**Issue by grantedfornothing** [Boldwork-AIproject/boldwork_frontend#5]
고객 선택 페이지 개발

**Comment by ganyunhee** [comment]
레이아웃 완성 (10.13)
코드 병합 (10.15)

<img width="758" alt="image" src="https://github.com/Boldwork-AIproject/boldwork_frontend/assets/81596122/549c0720-b0f0-45be-900a-2009b425dac8">
