### ISSUE TITLE
상담 분석 페이지 개발

### ISSUE THREAD

**Issue by grantedfornothing** [Boldwork-AIproject/boldwork_frontend#9]
상담 분석 페이지 개발

**Comment by ganyunhee** [comment]
레이아웃 완성 (10.17)

- 추후 오디오 플레이어, Plotly 그래프, 키워드 모델 넣을 예정

상담 내용
<img width="783" alt="image" src="https://github.com/Boldwork-AIproject/boldwork_frontend/assets/81596122/43c0a987-afc9-494c-8aa4-1086901056c5">

상담 분석
<img width="796" alt="image" src="https://github.com/Boldwork-AIproject/boldwork_frontend/assets/81596122/c83020a6-a90d-46a1-8d5d-07aab129b665">
